import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  Award, Clock, CheckCircle, ArrowLeft, 
  Share2, BarChart3, Target, Check as CheckIcon
} from 'lucide-react';
import { interviewAPI } from '../services/api';
import { formatDuration, getPerformanceLevel, formatSkillName } from '../utils/formatters';
import ScoreCard from '../components/ScoreCard';
import { RadarChart, PolarGrid, PolarAngleAxis, Radar, ResponsiveContainer } from 'recharts';

const Report = () => {
  const { sessionId } = useParams();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    loadReport();
  }, [sessionId]);

  const loadReport = async () => {
    try {
      const response = await interviewAPI.getReport(sessionId);
      if (response.success && response.report) {
        setReport(response.report);
      } else {
        setError('Report not available yet');
      }
    } catch (err) {
      console.error('Error loading report:', err);
      setError('Failed to load report. The interview may not be complete.');
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async () => {
    const shareUrl = `${window.location.origin}/report/${sessionId}`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Interview Report - ${report?.candidate_name}`,
          text: `Check out my interview performance: ${report?.overall_performance?.average_score}/25`,
          url: shareUrl,
        });
      } catch (err) {
        // Fallback to clipboard
        copyToClipboard(shareUrl);
      }
    } else {
      copyToClipboard(shareUrl);
    }
  };

  const copyToClipboard = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };
 
  const generateReportText = () => {
    if (!report) return '';
    
    let text = `CYBERHIRE AI - INTERVIEW REPORT\n`;
    text += `=====================================\n\n`;
    text += `Candidate: ${report.candidate_name}\n`;
    text += `Date: ${report.interview_date} at ${report.interview_time}\n`;
    text += `Duration: ${report.duration_minutes} minutes\n\n`;
    
    text += `OVERALL SCORE: ${report.overall_performance.average_score}/25 (${report.overall_performance.percentage}%)\n`;
    text += `Performance Level: ${report.overall_performance.performance_level}\n\n`;
    
    text += `SKILLS BREAKDOWN:\n`;
    text += `------------------\n`;
    
    Object.entries(report.skill_breakdown).forEach(([skill, data]) => {
      text += `\n${data.skill_name}: ${data.average_score}/25 (${data.percentage}%)\n`;
      text += `  Level: ${data.level}\n`;
      text += `  Responses: ${data.num_responses}\n`;
    });
    
    if (report.recommendations?.length > 0) {
      text += `\nRECOMMENDATIONS:\n`;
      text += `---------------\n`;
      report.recommendations.forEach((rec, i) => {
        text += `${i + 1}. ${rec}\n`;
      });
    }
    
    text += `\n=====================================\n`;
    text += `Generated by CyberHire AI\n`;
    
    return text;
  };

  if (loading) {
    return (
      <div className="min-h-screen pt-20 px-4 flex items-center justify-center bg-black">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-white/20 border-t-white rounded-full animate-spin mx-auto mb-4" />
          <p className="text-white-400">Loading your report...</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen pt-20 px-4 flex items-center justify-center bg-black">
        <div className="glass-card p-8 text-center max-w-md">
          <h2 className="text-2xl font-bold mb-2">Report Unavailable</h2>
          <p className="text-white-400 mb-6">{error}</p>
          <Link to="/" className="btn-primary inline-flex items-center gap-2">
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
        </div>
      </div>
    );
  }

  const performanceLevel = getPerformanceLevel(report.overall_performance.average_score);
  
  // Prepare radar chart data
  const radarData = Object.entries(report.skill_breakdown).map(([skill, data]) => ({
    skill: formatSkillName(skill),
    score: data.average_score,
    fullMark: 25,
  }));

  return (
    <div className="min-h-screen pt-20 pb-12 px-4 bg-black">
      <div className="max-w-6xl mx-auto">
        
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <Link 
            to="/" 
            className="inline-flex items-center gap-2 text-white-400 hover:text-white mb-4 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
          
          <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
            <div>
              <h1 className="text-4xl font-bold mb-2">Interview Report</h1>
              <p className="text-white-400">
                {report.candidate_name} • {report.interview_date} at {report.interview_time}
              </p>
            </div>
            
            <div className="flex gap-3">
              <button 
                onClick={handleShare}
                className="btn-secondary flex items-center gap-2"
              >
                {copied ? <CheckIcon className="w-4 h-4" /> : <Share2 className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Share'}
              </button>
            </div>
          </div>
        </motion.div>

        {/* Overall Performance Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="glass-card p-8 mb-8"
        >
          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 bg-white rounded-xl flex items-center justify-center">
              <Award className="w-6 h-6 text-black" />
            </div>
            <div>
              <h2 className="text-2xl font-bold">Overall Performance</h2>
              <p className="text-white-400">Based on {report.statistics.total_questions} questions</p>
            </div>
          </div>

          <div className="grid md:grid-cols-4 gap-6">
            {/* Overall Score */}
            <div className="md:col-span-2">
              <div className="flex items-end gap-4 mb-4">
                <div className="text-6xl font-bold">
                  {report.overall_performance.average_score}
                </div>
                <div className="text-3xl text-white-400 mb-2">/25</div>
              </div>
              
              <div className="w-full bg-white/10 rounded-full h-4 mb-3">
                <div
                  className="bg-white h-4 rounded-full transition-all duration-1000"
                  style={{ width: `${report.overall_performance.percentage}%` }}
                />
              </div>
              
              <div className="flex items-center gap-2">
                <span className="text-xl font-semibold">
                  {performanceLevel.level}
                </span>
              </div>
            </div>

            {/* Statistics */}
            <div className="space-y-4">
              <div>
                <div className="flex items-center gap-2 text-white-400 mb-1">
                  <Clock className="w-4 h-4" />
                  <span className="text-sm">Duration</span>
                </div>
                <p className="text-2xl font-bold">{formatDuration(report.duration_minutes)}</p>
              </div>
              
              <div>
                <div className="flex items-center gap-2 text-white-400 mb-1">
                  <BarChart3 className="w-4 h-4" />
                  <span className="text-sm">Avg Response</span>
                </div>
                <p className="text-2xl font-bold">{report.statistics.avg_response_length} words</p>
              </div>
            </div>

            <div className="space-y-4">
              <div>
                <div className="flex items-center gap-2 text-white-400 mb-1">
                  <CheckCircle className="w-4 h-4" />
                  <span className="text-sm">Questions</span>
                </div>
                <p className="text-2xl font-bold">{report.statistics.total_questions}</p>
              </div>
              
              <div>
                <div className="flex items-center gap-2 text-white-400 mb-1">
                  <Target className="w-4 h-4" />
                  <span className="text-sm">Percentage</span>
                </div>
                <p className="text-2xl font-bold">
                  {report.overall_performance.percentage}%
                </p>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Skills Breakdown */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="mb-8"
        >
          <h2 className="text-2xl font-bold mb-4">Skills Breakdown</h2>
          
          <div className="grid md:grid-cols-2 gap-6">
            {Object.entries(report.skill_breakdown).map(([skill, data], index) => (
              <motion.div
                key={skill}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.3 + index * 0.1 }}
              >
                <ScoreCard skill={skill} data={data} />
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Radar Chart */}
        {radarData.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="glass-card p-8 mb-8"
          >
            <h2 className="text-2xl font-bold mb-6">Skills Visualization</h2>
            
            <ResponsiveContainer width="100%" height={400}>
              <RadarChart data={radarData}>
                <PolarGrid stroke="rgba(255,255,255,0.1)" />
                <PolarAngleAxis 
                  dataKey="skill" 
                  tick={{ fill: 'rgba(255,255,255,0.6)', fontSize: 12 }}
                />
                <Radar
                  name="Score"
                  dataKey="score"
                  stroke="#FFFFFF"
                  fill="#FFFFFF"
                  fillOpacity={0.3}
                />
              </RadarChart>
            </ResponsiveContainer>
          </motion.div>
        )}

        {/* Recommendations */}
        {report.recommendations && report.recommendations.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 }}
            className="glass-card p-8"
          >
            <div className="flex items-center gap-3 mb-6">
              <div className="w-10 h-10 bg-white rounded-lg flex items-center justify-center">
                <Award className="w-5 h-5 text-black" />
              </div>
              <h2 className="text-2xl font-bold">Recommendations</h2>
            </div>
            
            <div className="space-y-4">
              {report.recommendations.map((rec, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.6 + index * 0.1 }}
                  className="flex gap-3 p-4 bg-white/5 rounded-xl border border-white/10"
                >
                  <div className="flex-shrink-0 w-8 h-8 bg-white rounded-lg flex items-center justify-center mt-1">
                    <span className="text-black font-bold">{index + 1}</span>
                  </div>
                  <p className="text-white-300 flex-1">{rec}</p>
                </motion.div>
              ))}
            </div>
          </motion.div>
        )}

        {/* Footer Actions */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.7 }}
          className="mt-8 text-center"
        >
          <Link to="/" className="btn-primary inline-flex items-center gap-2">
            Start New Interview
          </Link>
        </motion.div>
      </div>
    </div>
  );
};

export default Report;